serverId=nexus-snapshots
serverUsername="admin"
serverPassword="NjcNexus@123"
archeProfileId="acme"
archeTypeRepoId="archetype"
archeTypeRepoUrl="http://104.248.169.167:8081"
echo "<settings
    xmlns='http://maven.apache.org/SETTINGS/1.0.0'
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:schemaLocation='http://maven.apache.org/SETTINGS/1.0.0
                            https://maven.apache.org/xsd/settings-1.0.0.xsd'>
    <localRepository/>
    <interactiveMode/>
    <offline/>
    <pluginGroups/>
    <servers>
        <server>
            <id>nexus-snapshots</id>
            <username>${serverUsername}</username>
            <password>${serverPassword}</password>
        </server>
		<server>
            <id>maven-dependency-releases</id>
            <username>${serverUsername}</username>
            <password>${serverPassword}</password>
        </server> 
    </servers>
    <mirrors/>
    <proxies/>
    <profiles>
        <profile>
                <id>acme</id>
                <repositories>
                    <repository>
                        <id>archetype</id>
                        <url>${archeTypeRepoUrl}/repository/maven-snapshots/</url>
                        <releases>
                            <enabled>true</enabled>
                            <checksumPolicy>fail</checksumPolicy>
                        </releases>
                        <snapshots>
                            <enabled>true</enabled>
                            <checksumPolicy>warn</checksumPolicy>
                        </snapshots>
                    </repository>
					 <repository>
						  <id>maven-dependency-releases</id>
						  <name>maven-dependency-releases</name>
						  <url>${archeTypeRepoUrl}/repository/maven-dependency-releases/</url>
						  <layout>default</layout>
						  <releases>
							<enabled>true</enabled>
						  </releases>
						  <snapshots>
							<enabled>true</enabled>
						  </snapshots>
					</repository>
                </repositories>
            </profile>
		<profile>
            <id>Mule</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <repositories>
                <repository>
                    <id>mulesoft-releases</id>
                    <name>MuleSoft Repository</name>
                    <url>http://repository.mulesoft.org/releases/</url>
                    <layout>default</layout>
                </repository>
                <repository>
                    <id>mulesoft-snapshots</id>
                    <name>MuleSoft Snapshot Repository</name>
                    <url>http://repository.mulesoft.org/snapshots/</url>
                    <layout>default</layout>
                </repository>
                <repository>
                    <id>mulesoft-public</id>
                    <name>MuleSoft Public Repository</name>
                    <url>https://repository.mulesoft.org/nexus/content/repositories/public/</url>
                    <layout>default</layout>
                    <releases>
                        <enabled>true</enabled>
                    </releases>
                    <snapshots>
                        <enabled>true</enabled>
                    </snapshots>
                </repository>
                <repository>
                    <id>Repository</id>
                    <name>Corporate Repository</name>
                    <url>https://maven.anypoint.mulesoft.com/api/v2/organizations/maven</url>
                    <layout>default</layout>
                </repository>
            </repositories>
        </profile>
    </profiles>
    <activeProfiles/>
</settings>" > settings.xml